// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tribuo-regression-libsvm.proto

// Protobuf Java Version: 3.25.6
package org.tribuo.regression.libsvm.protos;

/**
 * <pre>
 *
 *LibSVMRegressionModel proto
 * </pre>
 *
 * Protobuf type {@code tribuo.regression.libsvm.LibSVMRegressionModelProto}
 */
public final class LibSVMRegressionModelProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tribuo.regression.libsvm.LibSVMRegressionModelProto)
    LibSVMRegressionModelProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LibSVMRegressionModelProto.newBuilder() to construct.
  private LibSVMRegressionModelProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LibSVMRegressionModelProto() {
    model_ = java.util.Collections.emptyList();
    means_ = emptyDoubleList();
    variances_ = emptyDoubleList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LibSVMRegressionModelProto();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.tribuo.regression.libsvm.protos.TribuoRegressionLibsvm.internal_static_tribuo_regression_libsvm_LibSVMRegressionModelProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.tribuo.regression.libsvm.protos.TribuoRegressionLibsvm.internal_static_tribuo_regression_libsvm_LibSVMRegressionModelProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto.class, org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto.Builder.class);
  }

  private int bitField0_;
  public static final int METADATA_FIELD_NUMBER = 1;
  private org.tribuo.protos.core.ModelDataProto metadata_;
  /**
   * <code>.tribuo.core.ModelDataProto metadata = 1;</code>
   * @return Whether the metadata field is set.
   */
  @java.lang.Override
  public boolean hasMetadata() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.tribuo.core.ModelDataProto metadata = 1;</code>
   * @return The metadata.
   */
  @java.lang.Override
  public org.tribuo.protos.core.ModelDataProto getMetadata() {
    return metadata_ == null ? org.tribuo.protos.core.ModelDataProto.getDefaultInstance() : metadata_;
  }
  /**
   * <code>.tribuo.core.ModelDataProto metadata = 1;</code>
   */
  @java.lang.Override
  public org.tribuo.protos.core.ModelDataProtoOrBuilder getMetadataOrBuilder() {
    return metadata_ == null ? org.tribuo.protos.core.ModelDataProto.getDefaultInstance() : metadata_;
  }

  public static final int MODEL_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<org.tribuo.common.libsvm.protos.SVMModelProto> model_;
  /**
   * <code>repeated .tribuo.common.libsvm.SVMModelProto model = 2;</code>
   */
  @java.lang.Override
  public java.util.List<org.tribuo.common.libsvm.protos.SVMModelProto> getModelList() {
    return model_;
  }
  /**
   * <code>repeated .tribuo.common.libsvm.SVMModelProto model = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.tribuo.common.libsvm.protos.SVMModelProtoOrBuilder> 
      getModelOrBuilderList() {
    return model_;
  }
  /**
   * <code>repeated .tribuo.common.libsvm.SVMModelProto model = 2;</code>
   */
  @java.lang.Override
  public int getModelCount() {
    return model_.size();
  }
  /**
   * <code>repeated .tribuo.common.libsvm.SVMModelProto model = 2;</code>
   */
  @java.lang.Override
  public org.tribuo.common.libsvm.protos.SVMModelProto getModel(int index) {
    return model_.get(index);
  }
  /**
   * <code>repeated .tribuo.common.libsvm.SVMModelProto model = 2;</code>
   */
  @java.lang.Override
  public org.tribuo.common.libsvm.protos.SVMModelProtoOrBuilder getModelOrBuilder(
      int index) {
    return model_.get(index);
  }

  public static final int MEANS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.DoubleList means_ =
      emptyDoubleList();
  /**
   * <code>repeated double means = 4;</code>
   * @return A list containing the means.
   */
  @java.lang.Override
  public java.util.List<java.lang.Double>
      getMeansList() {
    return means_;
  }
  /**
   * <code>repeated double means = 4;</code>
   * @return The count of means.
   */
  public int getMeansCount() {
    return means_.size();
  }
  /**
   * <code>repeated double means = 4;</code>
   * @param index The index of the element to return.
   * @return The means at the given index.
   */
  public double getMeans(int index) {
    return means_.getDouble(index);
  }
  private int meansMemoizedSerializedSize = -1;

  public static final int VARIANCES_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.DoubleList variances_ =
      emptyDoubleList();
  /**
   * <code>repeated double variances = 5;</code>
   * @return A list containing the variances.
   */
  @java.lang.Override
  public java.util.List<java.lang.Double>
      getVariancesList() {
    return variances_;
  }
  /**
   * <code>repeated double variances = 5;</code>
   * @return The count of variances.
   */
  public int getVariancesCount() {
    return variances_.size();
  }
  /**
   * <code>repeated double variances = 5;</code>
   * @param index The index of the element to return.
   * @return The variances at the given index.
   */
  public double getVariances(int index) {
    return variances_.getDouble(index);
  }
  private int variancesMemoizedSerializedSize = -1;

  public static final int STANDARDIZED_FIELD_NUMBER = 6;
  private boolean standardized_ = false;
  /**
   * <code>bool standardized = 6;</code>
   * @return The standardized.
   */
  @java.lang.Override
  public boolean getStandardized() {
    return standardized_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getMetadata());
    }
    for (int i = 0; i < model_.size(); i++) {
      output.writeMessage(2, model_.get(i));
    }
    if (getMeansList().size() > 0) {
      output.writeUInt32NoTag(34);
      output.writeUInt32NoTag(meansMemoizedSerializedSize);
    }
    for (int i = 0; i < means_.size(); i++) {
      output.writeDoubleNoTag(means_.getDouble(i));
    }
    if (getVariancesList().size() > 0) {
      output.writeUInt32NoTag(42);
      output.writeUInt32NoTag(variancesMemoizedSerializedSize);
    }
    for (int i = 0; i < variances_.size(); i++) {
      output.writeDoubleNoTag(variances_.getDouble(i));
    }
    if (standardized_ != false) {
      output.writeBool(6, standardized_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMetadata());
    }
    for (int i = 0; i < model_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, model_.get(i));
    }
    {
      int dataSize = 0;
      dataSize = 8 * getMeansList().size();
      size += dataSize;
      if (!getMeansList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      meansMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      dataSize = 8 * getVariancesList().size();
      size += dataSize;
      if (!getVariancesList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      variancesMemoizedSerializedSize = dataSize;
    }
    if (standardized_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, standardized_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto)) {
      return super.equals(obj);
    }
    org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto other = (org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto) obj;

    if (hasMetadata() != other.hasMetadata()) return false;
    if (hasMetadata()) {
      if (!getMetadata()
          .equals(other.getMetadata())) return false;
    }
    if (!getModelList()
        .equals(other.getModelList())) return false;
    if (!getMeansList()
        .equals(other.getMeansList())) return false;
    if (!getVariancesList()
        .equals(other.getVariancesList())) return false;
    if (getStandardized()
        != other.getStandardized()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMetadata()) {
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetadata().hashCode();
    }
    if (getModelCount() > 0) {
      hash = (37 * hash) + MODEL_FIELD_NUMBER;
      hash = (53 * hash) + getModelList().hashCode();
    }
    if (getMeansCount() > 0) {
      hash = (37 * hash) + MEANS_FIELD_NUMBER;
      hash = (53 * hash) + getMeansList().hashCode();
    }
    if (getVariancesCount() > 0) {
      hash = (37 * hash) + VARIANCES_FIELD_NUMBER;
      hash = (53 * hash) + getVariancesList().hashCode();
    }
    hash = (37 * hash) + STANDARDIZED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getStandardized());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *
   *LibSVMRegressionModel proto
   * </pre>
   *
   * Protobuf type {@code tribuo.regression.libsvm.LibSVMRegressionModelProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tribuo.regression.libsvm.LibSVMRegressionModelProto)
      org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tribuo.regression.libsvm.protos.TribuoRegressionLibsvm.internal_static_tribuo_regression_libsvm_LibSVMRegressionModelProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tribuo.regression.libsvm.protos.TribuoRegressionLibsvm.internal_static_tribuo_regression_libsvm_LibSVMRegressionModelProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto.class, org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto.Builder.class);
    }

    // Construct using org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMetadataFieldBuilder();
        getModelFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      metadata_ = null;
      if (metadataBuilder_ != null) {
        metadataBuilder_.dispose();
        metadataBuilder_ = null;
      }
      if (modelBuilder_ == null) {
        model_ = java.util.Collections.emptyList();
      } else {
        model_ = null;
        modelBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      means_ = emptyDoubleList();
      variances_ = emptyDoubleList();
      standardized_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.tribuo.regression.libsvm.protos.TribuoRegressionLibsvm.internal_static_tribuo_regression_libsvm_LibSVMRegressionModelProto_descriptor;
    }

    @java.lang.Override
    public org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto getDefaultInstanceForType() {
      return org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto.getDefaultInstance();
    }

    @java.lang.Override
    public org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto build() {
      org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto buildPartial() {
      org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto result = new org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto result) {
      if (modelBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          model_ = java.util.Collections.unmodifiableList(model_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.model_ = model_;
      } else {
        result.model_ = modelBuilder_.build();
      }
    }

    private void buildPartial0(org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.metadata_ = metadataBuilder_ == null
            ? metadata_
            : metadataBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        means_.makeImmutable();
        result.means_ = means_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        variances_.makeImmutable();
        result.variances_ = variances_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.standardized_ = standardized_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto) {
        return mergeFrom((org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto other) {
      if (other == org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto.getDefaultInstance()) return this;
      if (other.hasMetadata()) {
        mergeMetadata(other.getMetadata());
      }
      if (modelBuilder_ == null) {
        if (!other.model_.isEmpty()) {
          if (model_.isEmpty()) {
            model_ = other.model_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureModelIsMutable();
            model_.addAll(other.model_);
          }
          onChanged();
        }
      } else {
        if (!other.model_.isEmpty()) {
          if (modelBuilder_.isEmpty()) {
            modelBuilder_.dispose();
            modelBuilder_ = null;
            model_ = other.model_;
            bitField0_ = (bitField0_ & ~0x00000002);
            modelBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getModelFieldBuilder() : null;
          } else {
            modelBuilder_.addAllMessages(other.model_);
          }
        }
      }
      if (!other.means_.isEmpty()) {
        if (means_.isEmpty()) {
          means_ = other.means_;
          means_.makeImmutable();
          bitField0_ |= 0x00000004;
        } else {
          ensureMeansIsMutable();
          means_.addAll(other.means_);
        }
        onChanged();
      }
      if (!other.variances_.isEmpty()) {
        if (variances_.isEmpty()) {
          variances_ = other.variances_;
          variances_.makeImmutable();
          bitField0_ |= 0x00000008;
        } else {
          ensureVariancesIsMutable();
          variances_.addAll(other.variances_);
        }
        onChanged();
      }
      if (other.getStandardized() != false) {
        setStandardized(other.getStandardized());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getMetadataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              org.tribuo.common.libsvm.protos.SVMModelProto m =
                  input.readMessage(
                      org.tribuo.common.libsvm.protos.SVMModelProto.parser(),
                      extensionRegistry);
              if (modelBuilder_ == null) {
                ensureModelIsMutable();
                model_.add(m);
              } else {
                modelBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 33: {
              double v = input.readDouble();
              ensureMeansIsMutable();
              means_.addDouble(v);
              break;
            } // case 33
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              int alloc = length > 4096 ? 4096 : length;
              ensureMeansIsMutable(alloc / 8);
              while (input.getBytesUntilLimit() > 0) {
                means_.addDouble(input.readDouble());
              }
              input.popLimit(limit);
              break;
            } // case 34
            case 41: {
              double v = input.readDouble();
              ensureVariancesIsMutable();
              variances_.addDouble(v);
              break;
            } // case 41
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              int alloc = length > 4096 ? 4096 : length;
              ensureVariancesIsMutable(alloc / 8);
              while (input.getBytesUntilLimit() > 0) {
                variances_.addDouble(input.readDouble());
              }
              input.popLimit(limit);
              break;
            } // case 42
            case 48: {
              standardized_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private org.tribuo.protos.core.ModelDataProto metadata_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.tribuo.protos.core.ModelDataProto, org.tribuo.protos.core.ModelDataProto.Builder, org.tribuo.protos.core.ModelDataProtoOrBuilder> metadataBuilder_;
    /**
     * <code>.tribuo.core.ModelDataProto metadata = 1;</code>
     * @return Whether the metadata field is set.
     */
    public boolean hasMetadata() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.tribuo.core.ModelDataProto metadata = 1;</code>
     * @return The metadata.
     */
    public org.tribuo.protos.core.ModelDataProto getMetadata() {
      if (metadataBuilder_ == null) {
        return metadata_ == null ? org.tribuo.protos.core.ModelDataProto.getDefaultInstance() : metadata_;
      } else {
        return metadataBuilder_.getMessage();
      }
    }
    /**
     * <code>.tribuo.core.ModelDataProto metadata = 1;</code>
     */
    public Builder setMetadata(org.tribuo.protos.core.ModelDataProto value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metadata_ = value;
      } else {
        metadataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.tribuo.core.ModelDataProto metadata = 1;</code>
     */
    public Builder setMetadata(
        org.tribuo.protos.core.ModelDataProto.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        metadata_ = builderForValue.build();
      } else {
        metadataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.tribuo.core.ModelDataProto metadata = 1;</code>
     */
    public Builder mergeMetadata(org.tribuo.protos.core.ModelDataProto value) {
      if (metadataBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          metadata_ != null &&
          metadata_ != org.tribuo.protos.core.ModelDataProto.getDefaultInstance()) {
          getMetadataBuilder().mergeFrom(value);
        } else {
          metadata_ = value;
        }
      } else {
        metadataBuilder_.mergeFrom(value);
      }
      if (metadata_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.tribuo.core.ModelDataProto metadata = 1;</code>
     */
    public Builder clearMetadata() {
      bitField0_ = (bitField0_ & ~0x00000001);
      metadata_ = null;
      if (metadataBuilder_ != null) {
        metadataBuilder_.dispose();
        metadataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.tribuo.core.ModelDataProto metadata = 1;</code>
     */
    public org.tribuo.protos.core.ModelDataProto.Builder getMetadataBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getMetadataFieldBuilder().getBuilder();
    }
    /**
     * <code>.tribuo.core.ModelDataProto metadata = 1;</code>
     */
    public org.tribuo.protos.core.ModelDataProtoOrBuilder getMetadataOrBuilder() {
      if (metadataBuilder_ != null) {
        return metadataBuilder_.getMessageOrBuilder();
      } else {
        return metadata_ == null ?
            org.tribuo.protos.core.ModelDataProto.getDefaultInstance() : metadata_;
      }
    }
    /**
     * <code>.tribuo.core.ModelDataProto metadata = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.tribuo.protos.core.ModelDataProto, org.tribuo.protos.core.ModelDataProto.Builder, org.tribuo.protos.core.ModelDataProtoOrBuilder> 
        getMetadataFieldBuilder() {
      if (metadataBuilder_ == null) {
        metadataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.tribuo.protos.core.ModelDataProto, org.tribuo.protos.core.ModelDataProto.Builder, org.tribuo.protos.core.ModelDataProtoOrBuilder>(
                getMetadata(),
                getParentForChildren(),
                isClean());
        metadata_ = null;
      }
      return metadataBuilder_;
    }

    private java.util.List<org.tribuo.common.libsvm.protos.SVMModelProto> model_ =
      java.util.Collections.emptyList();
    private void ensureModelIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        model_ = new java.util.ArrayList<org.tribuo.common.libsvm.protos.SVMModelProto>(model_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.tribuo.common.libsvm.protos.SVMModelProto, org.tribuo.common.libsvm.protos.SVMModelProto.Builder, org.tribuo.common.libsvm.protos.SVMModelProtoOrBuilder> modelBuilder_;

    /**
     * <code>repeated .tribuo.common.libsvm.SVMModelProto model = 2;</code>
     */
    public java.util.List<org.tribuo.common.libsvm.protos.SVMModelProto> getModelList() {
      if (modelBuilder_ == null) {
        return java.util.Collections.unmodifiableList(model_);
      } else {
        return modelBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tribuo.common.libsvm.SVMModelProto model = 2;</code>
     */
    public int getModelCount() {
      if (modelBuilder_ == null) {
        return model_.size();
      } else {
        return modelBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tribuo.common.libsvm.SVMModelProto model = 2;</code>
     */
    public org.tribuo.common.libsvm.protos.SVMModelProto getModel(int index) {
      if (modelBuilder_ == null) {
        return model_.get(index);
      } else {
        return modelBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tribuo.common.libsvm.SVMModelProto model = 2;</code>
     */
    public Builder setModel(
        int index, org.tribuo.common.libsvm.protos.SVMModelProto value) {
      if (modelBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureModelIsMutable();
        model_.set(index, value);
        onChanged();
      } else {
        modelBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tribuo.common.libsvm.SVMModelProto model = 2;</code>
     */
    public Builder setModel(
        int index, org.tribuo.common.libsvm.protos.SVMModelProto.Builder builderForValue) {
      if (modelBuilder_ == null) {
        ensureModelIsMutable();
        model_.set(index, builderForValue.build());
        onChanged();
      } else {
        modelBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tribuo.common.libsvm.SVMModelProto model = 2;</code>
     */
    public Builder addModel(org.tribuo.common.libsvm.protos.SVMModelProto value) {
      if (modelBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureModelIsMutable();
        model_.add(value);
        onChanged();
      } else {
        modelBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tribuo.common.libsvm.SVMModelProto model = 2;</code>
     */
    public Builder addModel(
        int index, org.tribuo.common.libsvm.protos.SVMModelProto value) {
      if (modelBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureModelIsMutable();
        model_.add(index, value);
        onChanged();
      } else {
        modelBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tribuo.common.libsvm.SVMModelProto model = 2;</code>
     */
    public Builder addModel(
        org.tribuo.common.libsvm.protos.SVMModelProto.Builder builderForValue) {
      if (modelBuilder_ == null) {
        ensureModelIsMutable();
        model_.add(builderForValue.build());
        onChanged();
      } else {
        modelBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tribuo.common.libsvm.SVMModelProto model = 2;</code>
     */
    public Builder addModel(
        int index, org.tribuo.common.libsvm.protos.SVMModelProto.Builder builderForValue) {
      if (modelBuilder_ == null) {
        ensureModelIsMutable();
        model_.add(index, builderForValue.build());
        onChanged();
      } else {
        modelBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tribuo.common.libsvm.SVMModelProto model = 2;</code>
     */
    public Builder addAllModel(
        java.lang.Iterable<? extends org.tribuo.common.libsvm.protos.SVMModelProto> values) {
      if (modelBuilder_ == null) {
        ensureModelIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, model_);
        onChanged();
      } else {
        modelBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tribuo.common.libsvm.SVMModelProto model = 2;</code>
     */
    public Builder clearModel() {
      if (modelBuilder_ == null) {
        model_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        modelBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tribuo.common.libsvm.SVMModelProto model = 2;</code>
     */
    public Builder removeModel(int index) {
      if (modelBuilder_ == null) {
        ensureModelIsMutable();
        model_.remove(index);
        onChanged();
      } else {
        modelBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tribuo.common.libsvm.SVMModelProto model = 2;</code>
     */
    public org.tribuo.common.libsvm.protos.SVMModelProto.Builder getModelBuilder(
        int index) {
      return getModelFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tribuo.common.libsvm.SVMModelProto model = 2;</code>
     */
    public org.tribuo.common.libsvm.protos.SVMModelProtoOrBuilder getModelOrBuilder(
        int index) {
      if (modelBuilder_ == null) {
        return model_.get(index);  } else {
        return modelBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tribuo.common.libsvm.SVMModelProto model = 2;</code>
     */
    public java.util.List<? extends org.tribuo.common.libsvm.protos.SVMModelProtoOrBuilder> 
         getModelOrBuilderList() {
      if (modelBuilder_ != null) {
        return modelBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(model_);
      }
    }
    /**
     * <code>repeated .tribuo.common.libsvm.SVMModelProto model = 2;</code>
     */
    public org.tribuo.common.libsvm.protos.SVMModelProto.Builder addModelBuilder() {
      return getModelFieldBuilder().addBuilder(
          org.tribuo.common.libsvm.protos.SVMModelProto.getDefaultInstance());
    }
    /**
     * <code>repeated .tribuo.common.libsvm.SVMModelProto model = 2;</code>
     */
    public org.tribuo.common.libsvm.protos.SVMModelProto.Builder addModelBuilder(
        int index) {
      return getModelFieldBuilder().addBuilder(
          index, org.tribuo.common.libsvm.protos.SVMModelProto.getDefaultInstance());
    }
    /**
     * <code>repeated .tribuo.common.libsvm.SVMModelProto model = 2;</code>
     */
    public java.util.List<org.tribuo.common.libsvm.protos.SVMModelProto.Builder> 
         getModelBuilderList() {
      return getModelFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.tribuo.common.libsvm.protos.SVMModelProto, org.tribuo.common.libsvm.protos.SVMModelProto.Builder, org.tribuo.common.libsvm.protos.SVMModelProtoOrBuilder> 
        getModelFieldBuilder() {
      if (modelBuilder_ == null) {
        modelBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.tribuo.common.libsvm.protos.SVMModelProto, org.tribuo.common.libsvm.protos.SVMModelProto.Builder, org.tribuo.common.libsvm.protos.SVMModelProtoOrBuilder>(
                model_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        model_ = null;
      }
      return modelBuilder_;
    }

    private com.google.protobuf.Internal.DoubleList means_ = emptyDoubleList();
    private void ensureMeansIsMutable() {
      if (!means_.isModifiable()) {
        means_ = makeMutableCopy(means_);
      }
      bitField0_ |= 0x00000004;
    }
    private void ensureMeansIsMutable(int capacity) {
      if (!means_.isModifiable()) {
        means_ = makeMutableCopy(means_, capacity);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>repeated double means = 4;</code>
     * @return A list containing the means.
     */
    public java.util.List<java.lang.Double>
        getMeansList() {
      means_.makeImmutable();
      return means_;
    }
    /**
     * <code>repeated double means = 4;</code>
     * @return The count of means.
     */
    public int getMeansCount() {
      return means_.size();
    }
    /**
     * <code>repeated double means = 4;</code>
     * @param index The index of the element to return.
     * @return The means at the given index.
     */
    public double getMeans(int index) {
      return means_.getDouble(index);
    }
    /**
     * <code>repeated double means = 4;</code>
     * @param index The index to set the value at.
     * @param value The means to set.
     * @return This builder for chaining.
     */
    public Builder setMeans(
        int index, double value) {

      ensureMeansIsMutable();
      means_.setDouble(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated double means = 4;</code>
     * @param value The means to add.
     * @return This builder for chaining.
     */
    public Builder addMeans(double value) {

      ensureMeansIsMutable();
      means_.addDouble(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated double means = 4;</code>
     * @param values The means to add.
     * @return This builder for chaining.
     */
    public Builder addAllMeans(
        java.lang.Iterable<? extends java.lang.Double> values) {
      ensureMeansIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, means_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated double means = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMeans() {
      means_ = emptyDoubleList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.DoubleList variances_ = emptyDoubleList();
    private void ensureVariancesIsMutable() {
      if (!variances_.isModifiable()) {
        variances_ = makeMutableCopy(variances_);
      }
      bitField0_ |= 0x00000008;
    }
    private void ensureVariancesIsMutable(int capacity) {
      if (!variances_.isModifiable()) {
        variances_ = makeMutableCopy(variances_, capacity);
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <code>repeated double variances = 5;</code>
     * @return A list containing the variances.
     */
    public java.util.List<java.lang.Double>
        getVariancesList() {
      variances_.makeImmutable();
      return variances_;
    }
    /**
     * <code>repeated double variances = 5;</code>
     * @return The count of variances.
     */
    public int getVariancesCount() {
      return variances_.size();
    }
    /**
     * <code>repeated double variances = 5;</code>
     * @param index The index of the element to return.
     * @return The variances at the given index.
     */
    public double getVariances(int index) {
      return variances_.getDouble(index);
    }
    /**
     * <code>repeated double variances = 5;</code>
     * @param index The index to set the value at.
     * @param value The variances to set.
     * @return This builder for chaining.
     */
    public Builder setVariances(
        int index, double value) {

      ensureVariancesIsMutable();
      variances_.setDouble(index, value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated double variances = 5;</code>
     * @param value The variances to add.
     * @return This builder for chaining.
     */
    public Builder addVariances(double value) {

      ensureVariancesIsMutable();
      variances_.addDouble(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated double variances = 5;</code>
     * @param values The variances to add.
     * @return This builder for chaining.
     */
    public Builder addAllVariances(
        java.lang.Iterable<? extends java.lang.Double> values) {
      ensureVariancesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, variances_);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated double variances = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearVariances() {
      variances_ = emptyDoubleList();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }

    private boolean standardized_ ;
    /**
     * <code>bool standardized = 6;</code>
     * @return The standardized.
     */
    @java.lang.Override
    public boolean getStandardized() {
      return standardized_;
    }
    /**
     * <code>bool standardized = 6;</code>
     * @param value The standardized to set.
     * @return This builder for chaining.
     */
    public Builder setStandardized(boolean value) {

      standardized_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>bool standardized = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearStandardized() {
      bitField0_ = (bitField0_ & ~0x00000010);
      standardized_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tribuo.regression.libsvm.LibSVMRegressionModelProto)
  }

  // @@protoc_insertion_point(class_scope:tribuo.regression.libsvm.LibSVMRegressionModelProto)
  private static final org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto();
  }

  public static org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LibSVMRegressionModelProto>
      PARSER = new com.google.protobuf.AbstractParser<LibSVMRegressionModelProto>() {
    @java.lang.Override
    public LibSVMRegressionModelProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LibSVMRegressionModelProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LibSVMRegressionModelProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.tribuo.regression.libsvm.protos.LibSVMRegressionModelProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

