// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tribuo-tree.proto

package org.tribuo.common.tree.protos;

public interface TreeModelProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tribuo.common.tree.TreeModelProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tribuo.core.ModelDataProto metadata = 1;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <code>.tribuo.core.ModelDataProto metadata = 1;</code>
   * @return The metadata.
   */
  org.tribuo.protos.core.ModelDataProto getMetadata();
  /**
   * <code>.tribuo.core.ModelDataProto metadata = 1;</code>
   */
  org.tribuo.protos.core.ModelDataProtoOrBuilder getMetadataOrBuilder();

  /**
   * <code>repeated .tribuo.common.tree.TreeNodeProto nodes = 2;</code>
   */
  java.util.List<org.tribuo.common.tree.protos.TreeNodeProto> 
      getNodesList();
  /**
   * <code>repeated .tribuo.common.tree.TreeNodeProto nodes = 2;</code>
   */
  org.tribuo.common.tree.protos.TreeNodeProto getNodes(int index);
  /**
   * <code>repeated .tribuo.common.tree.TreeNodeProto nodes = 2;</code>
   */
  int getNodesCount();
  /**
   * <code>repeated .tribuo.common.tree.TreeNodeProto nodes = 2;</code>
   */
  java.util.List<? extends org.tribuo.common.tree.protos.TreeNodeProtoOrBuilder> 
      getNodesOrBuilderList();
  /**
   * <code>repeated .tribuo.common.tree.TreeNodeProto nodes = 2;</code>
   */
  org.tribuo.common.tree.protos.TreeNodeProtoOrBuilder getNodesOrBuilder(
      int index);
}
