// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tribuo-onnx.proto
// Protobuf Java Version: 4.33.4

package org.tribuo.interop.onnx.protos;

@com.google.protobuf.Generated
public interface LabelTransformerProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tribuo.interop.onnx.LabelTransformerProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool generates_probabilities = 1;</code>
   * @return The generatesProbabilities.
   */
  boolean getGeneratesProbabilities();
}
