// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tribuo-clustering-hdbscan.proto

package org.tribuo.clustering.hdbscan.protos;

public interface ClusterExemplarProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tribuo.clustering.hdbscan.ClusterExemplarProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 label = 1;</code>
   * @return The label.
   */
  int getLabel();

  /**
   * <code>double outlier_score = 2;</code>
   * @return The outlierScore.
   */
  double getOutlierScore();

  /**
   * <code>.tribuo.math.TensorProto features = 3;</code>
   * @return Whether the features field is set.
   */
  boolean hasFeatures();
  /**
   * <code>.tribuo.math.TensorProto features = 3;</code>
   * @return The features.
   */
  org.tribuo.math.protos.TensorProto getFeatures();
  /**
   * <code>.tribuo.math.TensorProto features = 3;</code>
   */
  org.tribuo.math.protos.TensorProtoOrBuilder getFeaturesOrBuilder();

  /**
   * <code>double max_dist_to_edge = 4;</code>
   * @return The maxDistToEdge.
   */
  double getMaxDistToEdge();
}
