// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tribuo-clustering-gmm.proto

// Protobuf Java Version: 3.25.3
package org.tribuo.clustering.gmm.protos;

public interface GaussianMixtureModelProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tribuo.clustering.gmm.GaussianMixtureModelProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tribuo.core.ModelDataProto metadata = 1;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <code>.tribuo.core.ModelDataProto metadata = 1;</code>
   * @return The metadata.
   */
  org.tribuo.protos.core.ModelDataProto getMetadata();
  /**
   * <code>.tribuo.core.ModelDataProto metadata = 1;</code>
   */
  org.tribuo.protos.core.ModelDataProtoOrBuilder getMetadataOrBuilder();

  /**
   * <code>.tribuo.math.TensorProto mixing_distribution = 2;</code>
   * @return Whether the mixingDistribution field is set.
   */
  boolean hasMixingDistribution();
  /**
   * <code>.tribuo.math.TensorProto mixing_distribution = 2;</code>
   * @return The mixingDistribution.
   */
  org.tribuo.math.protos.TensorProto getMixingDistribution();
  /**
   * <code>.tribuo.math.TensorProto mixing_distribution = 2;</code>
   */
  org.tribuo.math.protos.TensorProtoOrBuilder getMixingDistributionOrBuilder();

  /**
   * <code>repeated .tribuo.math.TensorProto mean_vectors = 3;</code>
   */
  java.util.List<org.tribuo.math.protos.TensorProto> 
      getMeanVectorsList();
  /**
   * <code>repeated .tribuo.math.TensorProto mean_vectors = 3;</code>
   */
  org.tribuo.math.protos.TensorProto getMeanVectors(int index);
  /**
   * <code>repeated .tribuo.math.TensorProto mean_vectors = 3;</code>
   */
  int getMeanVectorsCount();
  /**
   * <code>repeated .tribuo.math.TensorProto mean_vectors = 3;</code>
   */
  java.util.List<? extends org.tribuo.math.protos.TensorProtoOrBuilder> 
      getMeanVectorsOrBuilderList();
  /**
   * <code>repeated .tribuo.math.TensorProto mean_vectors = 3;</code>
   */
  org.tribuo.math.protos.TensorProtoOrBuilder getMeanVectorsOrBuilder(
      int index);

  /**
   * <code>repeated .tribuo.math.TensorProto covariance_matrices = 4;</code>
   */
  java.util.List<org.tribuo.math.protos.TensorProto> 
      getCovarianceMatricesList();
  /**
   * <code>repeated .tribuo.math.TensorProto covariance_matrices = 4;</code>
   */
  org.tribuo.math.protos.TensorProto getCovarianceMatrices(int index);
  /**
   * <code>repeated .tribuo.math.TensorProto covariance_matrices = 4;</code>
   */
  int getCovarianceMatricesCount();
  /**
   * <code>repeated .tribuo.math.TensorProto covariance_matrices = 4;</code>
   */
  java.util.List<? extends org.tribuo.math.protos.TensorProtoOrBuilder> 
      getCovarianceMatricesOrBuilderList();
  /**
   * <code>repeated .tribuo.math.TensorProto covariance_matrices = 4;</code>
   */
  org.tribuo.math.protos.TensorProtoOrBuilder getCovarianceMatricesOrBuilder(
      int index);

  /**
   * <code>.tribuo.clustering.gmm.GaussianMixtureModelProto.CovarianceTypeProto covariance_type = 5;</code>
   * @return The enum numeric value on the wire for covarianceType.
   */
  int getCovarianceTypeValue();
  /**
   * <code>.tribuo.clustering.gmm.GaussianMixtureModelProto.CovarianceTypeProto covariance_type = 5;</code>
   * @return The covarianceType.
   */
  org.tribuo.clustering.gmm.protos.GaussianMixtureModelProto.CovarianceTypeProto getCovarianceType();
}
