// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tribuo-core.proto

package org.tribuo.protos.core;

public interface DatasetDataProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tribuo.core.DatasetDataProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.olcut.RootProvenanceProto provenance = 1;</code>
   * @return Whether the provenance field is set.
   */
  boolean hasProvenance();
  /**
   * <code>.olcut.RootProvenanceProto provenance = 1;</code>
   * @return The provenance.
   */
  com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto getProvenance();
  /**
   * <code>.olcut.RootProvenanceProto provenance = 1;</code>
   */
  com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProtoOrBuilder getProvenanceOrBuilder();

  /**
   * <code>.tribuo.core.FeatureDomainProto feature_domain = 2;</code>
   * @return Whether the featureDomain field is set.
   */
  boolean hasFeatureDomain();
  /**
   * <code>.tribuo.core.FeatureDomainProto feature_domain = 2;</code>
   * @return The featureDomain.
   */
  org.tribuo.protos.core.FeatureDomainProto getFeatureDomain();
  /**
   * <code>.tribuo.core.FeatureDomainProto feature_domain = 2;</code>
   */
  org.tribuo.protos.core.FeatureDomainProtoOrBuilder getFeatureDomainOrBuilder();

  /**
   * <code>.tribuo.core.OutputDomainProto output_domain = 3;</code>
   * @return Whether the outputDomain field is set.
   */
  boolean hasOutputDomain();
  /**
   * <code>.tribuo.core.OutputDomainProto output_domain = 3;</code>
   * @return The outputDomain.
   */
  org.tribuo.protos.core.OutputDomainProto getOutputDomain();
  /**
   * <code>.tribuo.core.OutputDomainProto output_domain = 3;</code>
   */
  org.tribuo.protos.core.OutputDomainProtoOrBuilder getOutputDomainOrBuilder();

  /**
   * <code>repeated .olcut.RootProvenanceProto transform_provenance = 4;</code>
   */
  java.util.List<com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto> 
      getTransformProvenanceList();
  /**
   * <code>repeated .olcut.RootProvenanceProto transform_provenance = 4;</code>
   */
  com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto getTransformProvenance(int index);
  /**
   * <code>repeated .olcut.RootProvenanceProto transform_provenance = 4;</code>
   */
  int getTransformProvenanceCount();
  /**
   * <code>repeated .olcut.RootProvenanceProto transform_provenance = 4;</code>
   */
  java.util.List<? extends com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProtoOrBuilder> 
      getTransformProvenanceOrBuilderList();
  /**
   * <code>repeated .olcut.RootProvenanceProto transform_provenance = 4;</code>
   */
  com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProtoOrBuilder getTransformProvenanceOrBuilder(
      int index);

  /**
   * <code>.tribuo.core.OutputFactoryProto output_factory = 5;</code>
   * @return Whether the outputFactory field is set.
   */
  boolean hasOutputFactory();
  /**
   * <code>.tribuo.core.OutputFactoryProto output_factory = 5;</code>
   * @return The outputFactory.
   */
  org.tribuo.protos.core.OutputFactoryProto getOutputFactory();
  /**
   * <code>.tribuo.core.OutputFactoryProto output_factory = 5;</code>
   */
  org.tribuo.protos.core.OutputFactoryProtoOrBuilder getOutputFactoryOrBuilder();

  /**
   * <code>string tribuo_version = 6;</code>
   * @return The tribuoVersion.
   */
  java.lang.String getTribuoVersion();
  /**
   * <code>string tribuo_version = 6;</code>
   * @return The bytes for tribuoVersion.
   */
  com.google.protobuf.ByteString
      getTribuoVersionBytes();
}
