// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tribuo-core-impl.proto

// Protobuf Java Version: 3.25.6
package org.tribuo.protos.core;

public interface IndependentSequenceModelProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tribuo.core.IndependentSequenceModelProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tribuo.core.ModelDataProto metadata = 1;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <code>.tribuo.core.ModelDataProto metadata = 1;</code>
   * @return The metadata.
   */
  org.tribuo.protos.core.ModelDataProto getMetadata();
  /**
   * <code>.tribuo.core.ModelDataProto metadata = 1;</code>
   */
  org.tribuo.protos.core.ModelDataProtoOrBuilder getMetadataOrBuilder();

  /**
   * <code>.tribuo.core.ModelProto model = 2;</code>
   * @return Whether the model field is set.
   */
  boolean hasModel();
  /**
   * <code>.tribuo.core.ModelProto model = 2;</code>
   * @return The model.
   */
  org.tribuo.protos.core.ModelProto getModel();
  /**
   * <code>.tribuo.core.ModelProto model = 2;</code>
   */
  org.tribuo.protos.core.ModelProtoOrBuilder getModelOrBuilder();
}
