// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tribuo-core.proto

package org.tribuo.protos.core;

/**
 * <pre>
 *Model data proto containing shared model fields
 * </pre>
 *
 * Protobuf type {@code tribuo.core.ModelDataProto}
 */
public final class ModelDataProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tribuo.core.ModelDataProto)
    ModelDataProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ModelDataProto.newBuilder() to construct.
  private ModelDataProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ModelDataProto() {
    name_ = "";
    tribuoVersion_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ModelDataProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ModelDataProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto.Builder subBuilder = null;
            if (provenance_ != null) {
              subBuilder = provenance_.toBuilder();
            }
            provenance_ = input.readMessage(com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(provenance_);
              provenance_ = subBuilder.buildPartial();
            }

            break;
          }
          case 24: {

            generateProbabilities_ = input.readBool();
            break;
          }
          case 34: {
            org.tribuo.protos.core.FeatureDomainProto.Builder subBuilder = null;
            if (featureDomain_ != null) {
              subBuilder = featureDomain_.toBuilder();
            }
            featureDomain_ = input.readMessage(org.tribuo.protos.core.FeatureDomainProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(featureDomain_);
              featureDomain_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            org.tribuo.protos.core.OutputDomainProto.Builder subBuilder = null;
            if (outputDomain_ != null) {
              subBuilder = outputDomain_.toBuilder();
            }
            outputDomain_ = input.readMessage(org.tribuo.protos.core.OutputDomainProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(outputDomain_);
              outputDomain_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            tribuoVersion_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.tribuo.protos.core.TribuoCore.internal_static_tribuo_core_ModelDataProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.tribuo.protos.core.TribuoCore.internal_static_tribuo_core_ModelDataProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.tribuo.protos.core.ModelDataProto.class, org.tribuo.protos.core.ModelDataProto.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   *The model name
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *The model name
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROVENANCE_FIELD_NUMBER = 2;
  private com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto provenance_;
  /**
   * <pre>
   *The model provenance
   * </pre>
   *
   * <code>.olcut.RootProvenanceProto provenance = 2;</code>
   * @return Whether the provenance field is set.
   */
  @java.lang.Override
  public boolean hasProvenance() {
    return provenance_ != null;
  }
  /**
   * <pre>
   *The model provenance
   * </pre>
   *
   * <code>.olcut.RootProvenanceProto provenance = 2;</code>
   * @return The provenance.
   */
  @java.lang.Override
  public com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto getProvenance() {
    return provenance_ == null ? com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto.getDefaultInstance() : provenance_;
  }
  /**
   * <pre>
   *The model provenance
   * </pre>
   *
   * <code>.olcut.RootProvenanceProto provenance = 2;</code>
   */
  @java.lang.Override
  public com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProtoOrBuilder getProvenanceOrBuilder() {
    return getProvenance();
  }

  public static final int GENERATE_PROBABILITIES_FIELD_NUMBER = 3;
  private boolean generateProbabilities_;
  /**
   * <pre>
   *Does the model generate probabilities
   * </pre>
   *
   * <code>bool generate_probabilities = 3;</code>
   * @return The generateProbabilities.
   */
  @java.lang.Override
  public boolean getGenerateProbabilities() {
    return generateProbabilities_;
  }

  public static final int FEATURE_DOMAIN_FIELD_NUMBER = 4;
  private org.tribuo.protos.core.FeatureDomainProto featureDomain_;
  /**
   * <pre>
   *Model feature domain
   * </pre>
   *
   * <code>.tribuo.core.FeatureDomainProto feature_domain = 4;</code>
   * @return Whether the featureDomain field is set.
   */
  @java.lang.Override
  public boolean hasFeatureDomain() {
    return featureDomain_ != null;
  }
  /**
   * <pre>
   *Model feature domain
   * </pre>
   *
   * <code>.tribuo.core.FeatureDomainProto feature_domain = 4;</code>
   * @return The featureDomain.
   */
  @java.lang.Override
  public org.tribuo.protos.core.FeatureDomainProto getFeatureDomain() {
    return featureDomain_ == null ? org.tribuo.protos.core.FeatureDomainProto.getDefaultInstance() : featureDomain_;
  }
  /**
   * <pre>
   *Model feature domain
   * </pre>
   *
   * <code>.tribuo.core.FeatureDomainProto feature_domain = 4;</code>
   */
  @java.lang.Override
  public org.tribuo.protos.core.FeatureDomainProtoOrBuilder getFeatureDomainOrBuilder() {
    return getFeatureDomain();
  }

  public static final int OUTPUT_DOMAIN_FIELD_NUMBER = 5;
  private org.tribuo.protos.core.OutputDomainProto outputDomain_;
  /**
   * <pre>
   *Model output domain
   * </pre>
   *
   * <code>.tribuo.core.OutputDomainProto output_domain = 5;</code>
   * @return Whether the outputDomain field is set.
   */
  @java.lang.Override
  public boolean hasOutputDomain() {
    return outputDomain_ != null;
  }
  /**
   * <pre>
   *Model output domain
   * </pre>
   *
   * <code>.tribuo.core.OutputDomainProto output_domain = 5;</code>
   * @return The outputDomain.
   */
  @java.lang.Override
  public org.tribuo.protos.core.OutputDomainProto getOutputDomain() {
    return outputDomain_ == null ? org.tribuo.protos.core.OutputDomainProto.getDefaultInstance() : outputDomain_;
  }
  /**
   * <pre>
   *Model output domain
   * </pre>
   *
   * <code>.tribuo.core.OutputDomainProto output_domain = 5;</code>
   */
  @java.lang.Override
  public org.tribuo.protos.core.OutputDomainProtoOrBuilder getOutputDomainOrBuilder() {
    return getOutputDomain();
  }

  public static final int TRIBUO_VERSION_FIELD_NUMBER = 6;
  private volatile java.lang.Object tribuoVersion_;
  /**
   * <pre>
   *Tribuo version
   * </pre>
   *
   * <code>string tribuo_version = 6;</code>
   * @return The tribuoVersion.
   */
  @java.lang.Override
  public java.lang.String getTribuoVersion() {
    java.lang.Object ref = tribuoVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tribuoVersion_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *Tribuo version
   * </pre>
   *
   * <code>string tribuo_version = 6;</code>
   * @return The bytes for tribuoVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTribuoVersionBytes() {
    java.lang.Object ref = tribuoVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tribuoVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (provenance_ != null) {
      output.writeMessage(2, getProvenance());
    }
    if (generateProbabilities_ != false) {
      output.writeBool(3, generateProbabilities_);
    }
    if (featureDomain_ != null) {
      output.writeMessage(4, getFeatureDomain());
    }
    if (outputDomain_ != null) {
      output.writeMessage(5, getOutputDomain());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tribuoVersion_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, tribuoVersion_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (provenance_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getProvenance());
    }
    if (generateProbabilities_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, generateProbabilities_);
    }
    if (featureDomain_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getFeatureDomain());
    }
    if (outputDomain_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getOutputDomain());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tribuoVersion_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, tribuoVersion_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.tribuo.protos.core.ModelDataProto)) {
      return super.equals(obj);
    }
    org.tribuo.protos.core.ModelDataProto other = (org.tribuo.protos.core.ModelDataProto) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (hasProvenance() != other.hasProvenance()) return false;
    if (hasProvenance()) {
      if (!getProvenance()
          .equals(other.getProvenance())) return false;
    }
    if (getGenerateProbabilities()
        != other.getGenerateProbabilities()) return false;
    if (hasFeatureDomain() != other.hasFeatureDomain()) return false;
    if (hasFeatureDomain()) {
      if (!getFeatureDomain()
          .equals(other.getFeatureDomain())) return false;
    }
    if (hasOutputDomain() != other.hasOutputDomain()) return false;
    if (hasOutputDomain()) {
      if (!getOutputDomain()
          .equals(other.getOutputDomain())) return false;
    }
    if (!getTribuoVersion()
        .equals(other.getTribuoVersion())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (hasProvenance()) {
      hash = (37 * hash) + PROVENANCE_FIELD_NUMBER;
      hash = (53 * hash) + getProvenance().hashCode();
    }
    hash = (37 * hash) + GENERATE_PROBABILITIES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getGenerateProbabilities());
    if (hasFeatureDomain()) {
      hash = (37 * hash) + FEATURE_DOMAIN_FIELD_NUMBER;
      hash = (53 * hash) + getFeatureDomain().hashCode();
    }
    if (hasOutputDomain()) {
      hash = (37 * hash) + OUTPUT_DOMAIN_FIELD_NUMBER;
      hash = (53 * hash) + getOutputDomain().hashCode();
    }
    hash = (37 * hash) + TRIBUO_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getTribuoVersion().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.tribuo.protos.core.ModelDataProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tribuo.protos.core.ModelDataProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tribuo.protos.core.ModelDataProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tribuo.protos.core.ModelDataProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tribuo.protos.core.ModelDataProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tribuo.protos.core.ModelDataProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tribuo.protos.core.ModelDataProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tribuo.protos.core.ModelDataProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tribuo.protos.core.ModelDataProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.tribuo.protos.core.ModelDataProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tribuo.protos.core.ModelDataProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tribuo.protos.core.ModelDataProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.tribuo.protos.core.ModelDataProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *Model data proto containing shared model fields
   * </pre>
   *
   * Protobuf type {@code tribuo.core.ModelDataProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tribuo.core.ModelDataProto)
      org.tribuo.protos.core.ModelDataProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tribuo.protos.core.TribuoCore.internal_static_tribuo_core_ModelDataProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tribuo.protos.core.TribuoCore.internal_static_tribuo_core_ModelDataProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tribuo.protos.core.ModelDataProto.class, org.tribuo.protos.core.ModelDataProto.Builder.class);
    }

    // Construct using org.tribuo.protos.core.ModelDataProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      if (provenanceBuilder_ == null) {
        provenance_ = null;
      } else {
        provenance_ = null;
        provenanceBuilder_ = null;
      }
      generateProbabilities_ = false;

      if (featureDomainBuilder_ == null) {
        featureDomain_ = null;
      } else {
        featureDomain_ = null;
        featureDomainBuilder_ = null;
      }
      if (outputDomainBuilder_ == null) {
        outputDomain_ = null;
      } else {
        outputDomain_ = null;
        outputDomainBuilder_ = null;
      }
      tribuoVersion_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.tribuo.protos.core.TribuoCore.internal_static_tribuo_core_ModelDataProto_descriptor;
    }

    @java.lang.Override
    public org.tribuo.protos.core.ModelDataProto getDefaultInstanceForType() {
      return org.tribuo.protos.core.ModelDataProto.getDefaultInstance();
    }

    @java.lang.Override
    public org.tribuo.protos.core.ModelDataProto build() {
      org.tribuo.protos.core.ModelDataProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.tribuo.protos.core.ModelDataProto buildPartial() {
      org.tribuo.protos.core.ModelDataProto result = new org.tribuo.protos.core.ModelDataProto(this);
      result.name_ = name_;
      if (provenanceBuilder_ == null) {
        result.provenance_ = provenance_;
      } else {
        result.provenance_ = provenanceBuilder_.build();
      }
      result.generateProbabilities_ = generateProbabilities_;
      if (featureDomainBuilder_ == null) {
        result.featureDomain_ = featureDomain_;
      } else {
        result.featureDomain_ = featureDomainBuilder_.build();
      }
      if (outputDomainBuilder_ == null) {
        result.outputDomain_ = outputDomain_;
      } else {
        result.outputDomain_ = outputDomainBuilder_.build();
      }
      result.tribuoVersion_ = tribuoVersion_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.tribuo.protos.core.ModelDataProto) {
        return mergeFrom((org.tribuo.protos.core.ModelDataProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.tribuo.protos.core.ModelDataProto other) {
      if (other == org.tribuo.protos.core.ModelDataProto.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.hasProvenance()) {
        mergeProvenance(other.getProvenance());
      }
      if (other.getGenerateProbabilities() != false) {
        setGenerateProbabilities(other.getGenerateProbabilities());
      }
      if (other.hasFeatureDomain()) {
        mergeFeatureDomain(other.getFeatureDomain());
      }
      if (other.hasOutputDomain()) {
        mergeOutputDomain(other.getOutputDomain());
      }
      if (!other.getTribuoVersion().isEmpty()) {
        tribuoVersion_ = other.tribuoVersion_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.tribuo.protos.core.ModelDataProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.tribuo.protos.core.ModelDataProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     *The model name
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *The model name
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *The model name
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *The model name
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *The model name
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto provenance_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto, com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto.Builder, com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProtoOrBuilder> provenanceBuilder_;
    /**
     * <pre>
     *The model provenance
     * </pre>
     *
     * <code>.olcut.RootProvenanceProto provenance = 2;</code>
     * @return Whether the provenance field is set.
     */
    public boolean hasProvenance() {
      return provenanceBuilder_ != null || provenance_ != null;
    }
    /**
     * <pre>
     *The model provenance
     * </pre>
     *
     * <code>.olcut.RootProvenanceProto provenance = 2;</code>
     * @return The provenance.
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto getProvenance() {
      if (provenanceBuilder_ == null) {
        return provenance_ == null ? com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto.getDefaultInstance() : provenance_;
      } else {
        return provenanceBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *The model provenance
     * </pre>
     *
     * <code>.olcut.RootProvenanceProto provenance = 2;</code>
     */
    public Builder setProvenance(com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto value) {
      if (provenanceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        provenance_ = value;
        onChanged();
      } else {
        provenanceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *The model provenance
     * </pre>
     *
     * <code>.olcut.RootProvenanceProto provenance = 2;</code>
     */
    public Builder setProvenance(
        com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto.Builder builderForValue) {
      if (provenanceBuilder_ == null) {
        provenance_ = builderForValue.build();
        onChanged();
      } else {
        provenanceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *The model provenance
     * </pre>
     *
     * <code>.olcut.RootProvenanceProto provenance = 2;</code>
     */
    public Builder mergeProvenance(com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto value) {
      if (provenanceBuilder_ == null) {
        if (provenance_ != null) {
          provenance_ =
            com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto.newBuilder(provenance_).mergeFrom(value).buildPartial();
        } else {
          provenance_ = value;
        }
        onChanged();
      } else {
        provenanceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *The model provenance
     * </pre>
     *
     * <code>.olcut.RootProvenanceProto provenance = 2;</code>
     */
    public Builder clearProvenance() {
      if (provenanceBuilder_ == null) {
        provenance_ = null;
        onChanged();
      } else {
        provenance_ = null;
        provenanceBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *The model provenance
     * </pre>
     *
     * <code>.olcut.RootProvenanceProto provenance = 2;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto.Builder getProvenanceBuilder() {
      
      onChanged();
      return getProvenanceFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *The model provenance
     * </pre>
     *
     * <code>.olcut.RootProvenanceProto provenance = 2;</code>
     */
    public com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProtoOrBuilder getProvenanceOrBuilder() {
      if (provenanceBuilder_ != null) {
        return provenanceBuilder_.getMessageOrBuilder();
      } else {
        return provenance_ == null ?
            com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto.getDefaultInstance() : provenance_;
      }
    }
    /**
     * <pre>
     *The model provenance
     * </pre>
     *
     * <code>.olcut.RootProvenanceProto provenance = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto, com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto.Builder, com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProtoOrBuilder> 
        getProvenanceFieldBuilder() {
      if (provenanceBuilder_ == null) {
        provenanceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto, com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto.Builder, com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProtoOrBuilder>(
                getProvenance(),
                getParentForChildren(),
                isClean());
        provenance_ = null;
      }
      return provenanceBuilder_;
    }

    private boolean generateProbabilities_ ;
    /**
     * <pre>
     *Does the model generate probabilities
     * </pre>
     *
     * <code>bool generate_probabilities = 3;</code>
     * @return The generateProbabilities.
     */
    @java.lang.Override
    public boolean getGenerateProbabilities() {
      return generateProbabilities_;
    }
    /**
     * <pre>
     *Does the model generate probabilities
     * </pre>
     *
     * <code>bool generate_probabilities = 3;</code>
     * @param value The generateProbabilities to set.
     * @return This builder for chaining.
     */
    public Builder setGenerateProbabilities(boolean value) {
      
      generateProbabilities_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Does the model generate probabilities
     * </pre>
     *
     * <code>bool generate_probabilities = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearGenerateProbabilities() {
      
      generateProbabilities_ = false;
      onChanged();
      return this;
    }

    private org.tribuo.protos.core.FeatureDomainProto featureDomain_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.tribuo.protos.core.FeatureDomainProto, org.tribuo.protos.core.FeatureDomainProto.Builder, org.tribuo.protos.core.FeatureDomainProtoOrBuilder> featureDomainBuilder_;
    /**
     * <pre>
     *Model feature domain
     * </pre>
     *
     * <code>.tribuo.core.FeatureDomainProto feature_domain = 4;</code>
     * @return Whether the featureDomain field is set.
     */
    public boolean hasFeatureDomain() {
      return featureDomainBuilder_ != null || featureDomain_ != null;
    }
    /**
     * <pre>
     *Model feature domain
     * </pre>
     *
     * <code>.tribuo.core.FeatureDomainProto feature_domain = 4;</code>
     * @return The featureDomain.
     */
    public org.tribuo.protos.core.FeatureDomainProto getFeatureDomain() {
      if (featureDomainBuilder_ == null) {
        return featureDomain_ == null ? org.tribuo.protos.core.FeatureDomainProto.getDefaultInstance() : featureDomain_;
      } else {
        return featureDomainBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *Model feature domain
     * </pre>
     *
     * <code>.tribuo.core.FeatureDomainProto feature_domain = 4;</code>
     */
    public Builder setFeatureDomain(org.tribuo.protos.core.FeatureDomainProto value) {
      if (featureDomainBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        featureDomain_ = value;
        onChanged();
      } else {
        featureDomainBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *Model feature domain
     * </pre>
     *
     * <code>.tribuo.core.FeatureDomainProto feature_domain = 4;</code>
     */
    public Builder setFeatureDomain(
        org.tribuo.protos.core.FeatureDomainProto.Builder builderForValue) {
      if (featureDomainBuilder_ == null) {
        featureDomain_ = builderForValue.build();
        onChanged();
      } else {
        featureDomainBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *Model feature domain
     * </pre>
     *
     * <code>.tribuo.core.FeatureDomainProto feature_domain = 4;</code>
     */
    public Builder mergeFeatureDomain(org.tribuo.protos.core.FeatureDomainProto value) {
      if (featureDomainBuilder_ == null) {
        if (featureDomain_ != null) {
          featureDomain_ =
            org.tribuo.protos.core.FeatureDomainProto.newBuilder(featureDomain_).mergeFrom(value).buildPartial();
        } else {
          featureDomain_ = value;
        }
        onChanged();
      } else {
        featureDomainBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *Model feature domain
     * </pre>
     *
     * <code>.tribuo.core.FeatureDomainProto feature_domain = 4;</code>
     */
    public Builder clearFeatureDomain() {
      if (featureDomainBuilder_ == null) {
        featureDomain_ = null;
        onChanged();
      } else {
        featureDomain_ = null;
        featureDomainBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *Model feature domain
     * </pre>
     *
     * <code>.tribuo.core.FeatureDomainProto feature_domain = 4;</code>
     */
    public org.tribuo.protos.core.FeatureDomainProto.Builder getFeatureDomainBuilder() {
      
      onChanged();
      return getFeatureDomainFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *Model feature domain
     * </pre>
     *
     * <code>.tribuo.core.FeatureDomainProto feature_domain = 4;</code>
     */
    public org.tribuo.protos.core.FeatureDomainProtoOrBuilder getFeatureDomainOrBuilder() {
      if (featureDomainBuilder_ != null) {
        return featureDomainBuilder_.getMessageOrBuilder();
      } else {
        return featureDomain_ == null ?
            org.tribuo.protos.core.FeatureDomainProto.getDefaultInstance() : featureDomain_;
      }
    }
    /**
     * <pre>
     *Model feature domain
     * </pre>
     *
     * <code>.tribuo.core.FeatureDomainProto feature_domain = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.tribuo.protos.core.FeatureDomainProto, org.tribuo.protos.core.FeatureDomainProto.Builder, org.tribuo.protos.core.FeatureDomainProtoOrBuilder> 
        getFeatureDomainFieldBuilder() {
      if (featureDomainBuilder_ == null) {
        featureDomainBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.tribuo.protos.core.FeatureDomainProto, org.tribuo.protos.core.FeatureDomainProto.Builder, org.tribuo.protos.core.FeatureDomainProtoOrBuilder>(
                getFeatureDomain(),
                getParentForChildren(),
                isClean());
        featureDomain_ = null;
      }
      return featureDomainBuilder_;
    }

    private org.tribuo.protos.core.OutputDomainProto outputDomain_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.tribuo.protos.core.OutputDomainProto, org.tribuo.protos.core.OutputDomainProto.Builder, org.tribuo.protos.core.OutputDomainProtoOrBuilder> outputDomainBuilder_;
    /**
     * <pre>
     *Model output domain
     * </pre>
     *
     * <code>.tribuo.core.OutputDomainProto output_domain = 5;</code>
     * @return Whether the outputDomain field is set.
     */
    public boolean hasOutputDomain() {
      return outputDomainBuilder_ != null || outputDomain_ != null;
    }
    /**
     * <pre>
     *Model output domain
     * </pre>
     *
     * <code>.tribuo.core.OutputDomainProto output_domain = 5;</code>
     * @return The outputDomain.
     */
    public org.tribuo.protos.core.OutputDomainProto getOutputDomain() {
      if (outputDomainBuilder_ == null) {
        return outputDomain_ == null ? org.tribuo.protos.core.OutputDomainProto.getDefaultInstance() : outputDomain_;
      } else {
        return outputDomainBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *Model output domain
     * </pre>
     *
     * <code>.tribuo.core.OutputDomainProto output_domain = 5;</code>
     */
    public Builder setOutputDomain(org.tribuo.protos.core.OutputDomainProto value) {
      if (outputDomainBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        outputDomain_ = value;
        onChanged();
      } else {
        outputDomainBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *Model output domain
     * </pre>
     *
     * <code>.tribuo.core.OutputDomainProto output_domain = 5;</code>
     */
    public Builder setOutputDomain(
        org.tribuo.protos.core.OutputDomainProto.Builder builderForValue) {
      if (outputDomainBuilder_ == null) {
        outputDomain_ = builderForValue.build();
        onChanged();
      } else {
        outputDomainBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *Model output domain
     * </pre>
     *
     * <code>.tribuo.core.OutputDomainProto output_domain = 5;</code>
     */
    public Builder mergeOutputDomain(org.tribuo.protos.core.OutputDomainProto value) {
      if (outputDomainBuilder_ == null) {
        if (outputDomain_ != null) {
          outputDomain_ =
            org.tribuo.protos.core.OutputDomainProto.newBuilder(outputDomain_).mergeFrom(value).buildPartial();
        } else {
          outputDomain_ = value;
        }
        onChanged();
      } else {
        outputDomainBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *Model output domain
     * </pre>
     *
     * <code>.tribuo.core.OutputDomainProto output_domain = 5;</code>
     */
    public Builder clearOutputDomain() {
      if (outputDomainBuilder_ == null) {
        outputDomain_ = null;
        onChanged();
      } else {
        outputDomain_ = null;
        outputDomainBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *Model output domain
     * </pre>
     *
     * <code>.tribuo.core.OutputDomainProto output_domain = 5;</code>
     */
    public org.tribuo.protos.core.OutputDomainProto.Builder getOutputDomainBuilder() {
      
      onChanged();
      return getOutputDomainFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *Model output domain
     * </pre>
     *
     * <code>.tribuo.core.OutputDomainProto output_domain = 5;</code>
     */
    public org.tribuo.protos.core.OutputDomainProtoOrBuilder getOutputDomainOrBuilder() {
      if (outputDomainBuilder_ != null) {
        return outputDomainBuilder_.getMessageOrBuilder();
      } else {
        return outputDomain_ == null ?
            org.tribuo.protos.core.OutputDomainProto.getDefaultInstance() : outputDomain_;
      }
    }
    /**
     * <pre>
     *Model output domain
     * </pre>
     *
     * <code>.tribuo.core.OutputDomainProto output_domain = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.tribuo.protos.core.OutputDomainProto, org.tribuo.protos.core.OutputDomainProto.Builder, org.tribuo.protos.core.OutputDomainProtoOrBuilder> 
        getOutputDomainFieldBuilder() {
      if (outputDomainBuilder_ == null) {
        outputDomainBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.tribuo.protos.core.OutputDomainProto, org.tribuo.protos.core.OutputDomainProto.Builder, org.tribuo.protos.core.OutputDomainProtoOrBuilder>(
                getOutputDomain(),
                getParentForChildren(),
                isClean());
        outputDomain_ = null;
      }
      return outputDomainBuilder_;
    }

    private java.lang.Object tribuoVersion_ = "";
    /**
     * <pre>
     *Tribuo version
     * </pre>
     *
     * <code>string tribuo_version = 6;</code>
     * @return The tribuoVersion.
     */
    public java.lang.String getTribuoVersion() {
      java.lang.Object ref = tribuoVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tribuoVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *Tribuo version
     * </pre>
     *
     * <code>string tribuo_version = 6;</code>
     * @return The bytes for tribuoVersion.
     */
    public com.google.protobuf.ByteString
        getTribuoVersionBytes() {
      java.lang.Object ref = tribuoVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tribuoVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *Tribuo version
     * </pre>
     *
     * <code>string tribuo_version = 6;</code>
     * @param value The tribuoVersion to set.
     * @return This builder for chaining.
     */
    public Builder setTribuoVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tribuoVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Tribuo version
     * </pre>
     *
     * <code>string tribuo_version = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTribuoVersion() {
      
      tribuoVersion_ = getDefaultInstance().getTribuoVersion();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Tribuo version
     * </pre>
     *
     * <code>string tribuo_version = 6;</code>
     * @param value The bytes for tribuoVersion to set.
     * @return This builder for chaining.
     */
    public Builder setTribuoVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tribuoVersion_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tribuo.core.ModelDataProto)
  }

  // @@protoc_insertion_point(class_scope:tribuo.core.ModelDataProto)
  private static final org.tribuo.protos.core.ModelDataProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.tribuo.protos.core.ModelDataProto();
  }

  public static org.tribuo.protos.core.ModelDataProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ModelDataProto>
      PARSER = new com.google.protobuf.AbstractParser<ModelDataProto>() {
    @java.lang.Override
    public ModelDataProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ModelDataProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ModelDataProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ModelDataProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.tribuo.protos.core.ModelDataProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

