// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tribuo-core.proto

package org.tribuo.protos.core;

public interface PredictionProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tribuo.core.PredictionProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>string class_name = 2;</code>
   * @return The className.
   */
  java.lang.String getClassName();
  /**
   * <code>string class_name = 2;</code>
   * @return The bytes for className.
   */
  com.google.protobuf.ByteString
      getClassNameBytes();

  /**
   * <code>.tribuo.core.ExampleProto example = 3;</code>
   * @return Whether the example field is set.
   */
  boolean hasExample();
  /**
   * <code>.tribuo.core.ExampleProto example = 3;</code>
   * @return The example.
   */
  org.tribuo.protos.core.ExampleProto getExample();
  /**
   * <code>.tribuo.core.ExampleProto example = 3;</code>
   */
  org.tribuo.protos.core.ExampleProtoOrBuilder getExampleOrBuilder();

  /**
   * <code>.tribuo.core.OutputProto output = 4;</code>
   * @return Whether the output field is set.
   */
  boolean hasOutput();
  /**
   * <code>.tribuo.core.OutputProto output = 4;</code>
   * @return The output.
   */
  org.tribuo.protos.core.OutputProto getOutput();
  /**
   * <code>.tribuo.core.OutputProto output = 4;</code>
   */
  org.tribuo.protos.core.OutputProtoOrBuilder getOutputOrBuilder();

  /**
   * <code>bool probability = 5;</code>
   * @return The probability.
   */
  boolean getProbability();

  /**
   * <code>int32 num_used = 6;</code>
   * @return The numUsed.
   */
  int getNumUsed();

  /**
   * <code>int32 example_size = 7;</code>
   * @return The exampleSize.
   */
  int getExampleSize();

  /**
   * <code>map&lt;string, .tribuo.core.OutputProto&gt; output_scores = 8;</code>
   */
  int getOutputScoresCount();
  /**
   * <code>map&lt;string, .tribuo.core.OutputProto&gt; output_scores = 8;</code>
   */
  boolean containsOutputScores(
      java.lang.String key);
  /**
   * Use {@link #getOutputScoresMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, org.tribuo.protos.core.OutputProto>
  getOutputScores();
  /**
   * <code>map&lt;string, .tribuo.core.OutputProto&gt; output_scores = 8;</code>
   */
  java.util.Map<java.lang.String, org.tribuo.protos.core.OutputProto>
  getOutputScoresMap();
  /**
   * <code>map&lt;string, .tribuo.core.OutputProto&gt; output_scores = 8;</code>
   */

  org.tribuo.protos.core.OutputProto getOutputScoresOrDefault(
      java.lang.String key,
      org.tribuo.protos.core.OutputProto defaultValue);
  /**
   * <code>map&lt;string, .tribuo.core.OutputProto&gt; output_scores = 8;</code>
   */

  org.tribuo.protos.core.OutputProto getOutputScoresOrThrow(
      java.lang.String key);
}
