// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tribuo-core.proto

package org.tribuo.protos.core;

/**
 * <pre>
 *Transformer list proto
 * </pre>
 *
 * Protobuf type {@code tribuo.core.TransformerListProto}
 */
public final class TransformerListProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tribuo.core.TransformerListProto)
    TransformerListProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TransformerListProto.newBuilder() to construct.
  private TransformerListProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TransformerListProto() {
    transformer_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TransformerListProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TransformerListProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              transformer_ = new java.util.ArrayList<org.tribuo.protos.core.TransformerProto>();
              mutable_bitField0_ |= 0x00000001;
            }
            transformer_.add(
                input.readMessage(org.tribuo.protos.core.TransformerProto.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        transformer_ = java.util.Collections.unmodifiableList(transformer_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.tribuo.protos.core.TribuoCore.internal_static_tribuo_core_TransformerListProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.tribuo.protos.core.TribuoCore.internal_static_tribuo_core_TransformerListProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.tribuo.protos.core.TransformerListProto.class, org.tribuo.protos.core.TransformerListProto.Builder.class);
  }

  public static final int TRANSFORMER_FIELD_NUMBER = 1;
  private java.util.List<org.tribuo.protos.core.TransformerProto> transformer_;
  /**
   * <code>repeated .tribuo.core.TransformerProto transformer = 1;</code>
   */
  @java.lang.Override
  public java.util.List<org.tribuo.protos.core.TransformerProto> getTransformerList() {
    return transformer_;
  }
  /**
   * <code>repeated .tribuo.core.TransformerProto transformer = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.tribuo.protos.core.TransformerProtoOrBuilder> 
      getTransformerOrBuilderList() {
    return transformer_;
  }
  /**
   * <code>repeated .tribuo.core.TransformerProto transformer = 1;</code>
   */
  @java.lang.Override
  public int getTransformerCount() {
    return transformer_.size();
  }
  /**
   * <code>repeated .tribuo.core.TransformerProto transformer = 1;</code>
   */
  @java.lang.Override
  public org.tribuo.protos.core.TransformerProto getTransformer(int index) {
    return transformer_.get(index);
  }
  /**
   * <code>repeated .tribuo.core.TransformerProto transformer = 1;</code>
   */
  @java.lang.Override
  public org.tribuo.protos.core.TransformerProtoOrBuilder getTransformerOrBuilder(
      int index) {
    return transformer_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < transformer_.size(); i++) {
      output.writeMessage(1, transformer_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < transformer_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, transformer_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.tribuo.protos.core.TransformerListProto)) {
      return super.equals(obj);
    }
    org.tribuo.protos.core.TransformerListProto other = (org.tribuo.protos.core.TransformerListProto) obj;

    if (!getTransformerList()
        .equals(other.getTransformerList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTransformerCount() > 0) {
      hash = (37 * hash) + TRANSFORMER_FIELD_NUMBER;
      hash = (53 * hash) + getTransformerList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.tribuo.protos.core.TransformerListProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tribuo.protos.core.TransformerListProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tribuo.protos.core.TransformerListProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tribuo.protos.core.TransformerListProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tribuo.protos.core.TransformerListProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tribuo.protos.core.TransformerListProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tribuo.protos.core.TransformerListProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tribuo.protos.core.TransformerListProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tribuo.protos.core.TransformerListProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.tribuo.protos.core.TransformerListProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tribuo.protos.core.TransformerListProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tribuo.protos.core.TransformerListProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.tribuo.protos.core.TransformerListProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *Transformer list proto
   * </pre>
   *
   * Protobuf type {@code tribuo.core.TransformerListProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tribuo.core.TransformerListProto)
      org.tribuo.protos.core.TransformerListProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tribuo.protos.core.TribuoCore.internal_static_tribuo_core_TransformerListProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tribuo.protos.core.TribuoCore.internal_static_tribuo_core_TransformerListProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tribuo.protos.core.TransformerListProto.class, org.tribuo.protos.core.TransformerListProto.Builder.class);
    }

    // Construct using org.tribuo.protos.core.TransformerListProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTransformerFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (transformerBuilder_ == null) {
        transformer_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        transformerBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.tribuo.protos.core.TribuoCore.internal_static_tribuo_core_TransformerListProto_descriptor;
    }

    @java.lang.Override
    public org.tribuo.protos.core.TransformerListProto getDefaultInstanceForType() {
      return org.tribuo.protos.core.TransformerListProto.getDefaultInstance();
    }

    @java.lang.Override
    public org.tribuo.protos.core.TransformerListProto build() {
      org.tribuo.protos.core.TransformerListProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.tribuo.protos.core.TransformerListProto buildPartial() {
      org.tribuo.protos.core.TransformerListProto result = new org.tribuo.protos.core.TransformerListProto(this);
      int from_bitField0_ = bitField0_;
      if (transformerBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          transformer_ = java.util.Collections.unmodifiableList(transformer_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.transformer_ = transformer_;
      } else {
        result.transformer_ = transformerBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.tribuo.protos.core.TransformerListProto) {
        return mergeFrom((org.tribuo.protos.core.TransformerListProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.tribuo.protos.core.TransformerListProto other) {
      if (other == org.tribuo.protos.core.TransformerListProto.getDefaultInstance()) return this;
      if (transformerBuilder_ == null) {
        if (!other.transformer_.isEmpty()) {
          if (transformer_.isEmpty()) {
            transformer_ = other.transformer_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTransformerIsMutable();
            transformer_.addAll(other.transformer_);
          }
          onChanged();
        }
      } else {
        if (!other.transformer_.isEmpty()) {
          if (transformerBuilder_.isEmpty()) {
            transformerBuilder_.dispose();
            transformerBuilder_ = null;
            transformer_ = other.transformer_;
            bitField0_ = (bitField0_ & ~0x00000001);
            transformerBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTransformerFieldBuilder() : null;
          } else {
            transformerBuilder_.addAllMessages(other.transformer_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.tribuo.protos.core.TransformerListProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.tribuo.protos.core.TransformerListProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<org.tribuo.protos.core.TransformerProto> transformer_ =
      java.util.Collections.emptyList();
    private void ensureTransformerIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        transformer_ = new java.util.ArrayList<org.tribuo.protos.core.TransformerProto>(transformer_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.tribuo.protos.core.TransformerProto, org.tribuo.protos.core.TransformerProto.Builder, org.tribuo.protos.core.TransformerProtoOrBuilder> transformerBuilder_;

    /**
     * <code>repeated .tribuo.core.TransformerProto transformer = 1;</code>
     */
    public java.util.List<org.tribuo.protos.core.TransformerProto> getTransformerList() {
      if (transformerBuilder_ == null) {
        return java.util.Collections.unmodifiableList(transformer_);
      } else {
        return transformerBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tribuo.core.TransformerProto transformer = 1;</code>
     */
    public int getTransformerCount() {
      if (transformerBuilder_ == null) {
        return transformer_.size();
      } else {
        return transformerBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tribuo.core.TransformerProto transformer = 1;</code>
     */
    public org.tribuo.protos.core.TransformerProto getTransformer(int index) {
      if (transformerBuilder_ == null) {
        return transformer_.get(index);
      } else {
        return transformerBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tribuo.core.TransformerProto transformer = 1;</code>
     */
    public Builder setTransformer(
        int index, org.tribuo.protos.core.TransformerProto value) {
      if (transformerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransformerIsMutable();
        transformer_.set(index, value);
        onChanged();
      } else {
        transformerBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tribuo.core.TransformerProto transformer = 1;</code>
     */
    public Builder setTransformer(
        int index, org.tribuo.protos.core.TransformerProto.Builder builderForValue) {
      if (transformerBuilder_ == null) {
        ensureTransformerIsMutable();
        transformer_.set(index, builderForValue.build());
        onChanged();
      } else {
        transformerBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tribuo.core.TransformerProto transformer = 1;</code>
     */
    public Builder addTransformer(org.tribuo.protos.core.TransformerProto value) {
      if (transformerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransformerIsMutable();
        transformer_.add(value);
        onChanged();
      } else {
        transformerBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tribuo.core.TransformerProto transformer = 1;</code>
     */
    public Builder addTransformer(
        int index, org.tribuo.protos.core.TransformerProto value) {
      if (transformerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransformerIsMutable();
        transformer_.add(index, value);
        onChanged();
      } else {
        transformerBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tribuo.core.TransformerProto transformer = 1;</code>
     */
    public Builder addTransformer(
        org.tribuo.protos.core.TransformerProto.Builder builderForValue) {
      if (transformerBuilder_ == null) {
        ensureTransformerIsMutable();
        transformer_.add(builderForValue.build());
        onChanged();
      } else {
        transformerBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tribuo.core.TransformerProto transformer = 1;</code>
     */
    public Builder addTransformer(
        int index, org.tribuo.protos.core.TransformerProto.Builder builderForValue) {
      if (transformerBuilder_ == null) {
        ensureTransformerIsMutable();
        transformer_.add(index, builderForValue.build());
        onChanged();
      } else {
        transformerBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tribuo.core.TransformerProto transformer = 1;</code>
     */
    public Builder addAllTransformer(
        java.lang.Iterable<? extends org.tribuo.protos.core.TransformerProto> values) {
      if (transformerBuilder_ == null) {
        ensureTransformerIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, transformer_);
        onChanged();
      } else {
        transformerBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tribuo.core.TransformerProto transformer = 1;</code>
     */
    public Builder clearTransformer() {
      if (transformerBuilder_ == null) {
        transformer_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        transformerBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tribuo.core.TransformerProto transformer = 1;</code>
     */
    public Builder removeTransformer(int index) {
      if (transformerBuilder_ == null) {
        ensureTransformerIsMutable();
        transformer_.remove(index);
        onChanged();
      } else {
        transformerBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tribuo.core.TransformerProto transformer = 1;</code>
     */
    public org.tribuo.protos.core.TransformerProto.Builder getTransformerBuilder(
        int index) {
      return getTransformerFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tribuo.core.TransformerProto transformer = 1;</code>
     */
    public org.tribuo.protos.core.TransformerProtoOrBuilder getTransformerOrBuilder(
        int index) {
      if (transformerBuilder_ == null) {
        return transformer_.get(index);  } else {
        return transformerBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tribuo.core.TransformerProto transformer = 1;</code>
     */
    public java.util.List<? extends org.tribuo.protos.core.TransformerProtoOrBuilder> 
         getTransformerOrBuilderList() {
      if (transformerBuilder_ != null) {
        return transformerBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(transformer_);
      }
    }
    /**
     * <code>repeated .tribuo.core.TransformerProto transformer = 1;</code>
     */
    public org.tribuo.protos.core.TransformerProto.Builder addTransformerBuilder() {
      return getTransformerFieldBuilder().addBuilder(
          org.tribuo.protos.core.TransformerProto.getDefaultInstance());
    }
    /**
     * <code>repeated .tribuo.core.TransformerProto transformer = 1;</code>
     */
    public org.tribuo.protos.core.TransformerProto.Builder addTransformerBuilder(
        int index) {
      return getTransformerFieldBuilder().addBuilder(
          index, org.tribuo.protos.core.TransformerProto.getDefaultInstance());
    }
    /**
     * <code>repeated .tribuo.core.TransformerProto transformer = 1;</code>
     */
    public java.util.List<org.tribuo.protos.core.TransformerProto.Builder> 
         getTransformerBuilderList() {
      return getTransformerFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.tribuo.protos.core.TransformerProto, org.tribuo.protos.core.TransformerProto.Builder, org.tribuo.protos.core.TransformerProtoOrBuilder> 
        getTransformerFieldBuilder() {
      if (transformerBuilder_ == null) {
        transformerBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.tribuo.protos.core.TransformerProto, org.tribuo.protos.core.TransformerProto.Builder, org.tribuo.protos.core.TransformerProtoOrBuilder>(
                transformer_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        transformer_ = null;
      }
      return transformerBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tribuo.core.TransformerListProto)
  }

  // @@protoc_insertion_point(class_scope:tribuo.core.TransformerListProto)
  private static final org.tribuo.protos.core.TransformerListProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.tribuo.protos.core.TransformerListProto();
  }

  public static org.tribuo.protos.core.TransformerListProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TransformerListProto>
      PARSER = new com.google.protobuf.AbstractParser<TransformerListProto>() {
    @java.lang.Override
    public TransformerListProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TransformerListProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TransformerListProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TransformerListProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.tribuo.protos.core.TransformerListProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

