// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tribuo-core.proto

package org.tribuo.protos.core;

public interface TransformerMapProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tribuo.core.TransformerMapProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>map&lt;string, .tribuo.core.TransformerProto&gt; map = 2;</code>
   */
  int getMapCount();
  /**
   * <code>map&lt;string, .tribuo.core.TransformerProto&gt; map = 2;</code>
   */
  boolean containsMap(
      java.lang.String key);
  /**
   * Use {@link #getMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, org.tribuo.protos.core.TransformerProto>
  getMap();
  /**
   * <code>map&lt;string, .tribuo.core.TransformerProto&gt; map = 2;</code>
   */
  java.util.Map<java.lang.String, org.tribuo.protos.core.TransformerProto>
  getMapMap();
  /**
   * <code>map&lt;string, .tribuo.core.TransformerProto&gt; map = 2;</code>
   */

  org.tribuo.protos.core.TransformerProto getMapOrDefault(
      java.lang.String key,
      org.tribuo.protos.core.TransformerProto defaultValue);
  /**
   * <code>map&lt;string, .tribuo.core.TransformerProto&gt; map = 2;</code>
   */

  org.tribuo.protos.core.TransformerProto getMapOrThrow(
      java.lang.String key);

  /**
   * <code>.olcut.RootProvenanceProto datasetProvenance = 3;</code>
   * @return Whether the datasetProvenance field is set.
   */
  boolean hasDatasetProvenance();
  /**
   * <code>.olcut.RootProvenanceProto datasetProvenance = 3;</code>
   * @return The datasetProvenance.
   */
  com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto getDatasetProvenance();
  /**
   * <code>.olcut.RootProvenanceProto datasetProvenance = 3;</code>
   */
  com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProtoOrBuilder getDatasetProvenanceOrBuilder();

  /**
   * <code>.olcut.RootProvenanceProto transformationMapProvenance = 4;</code>
   * @return Whether the transformationMapProvenance field is set.
   */
  boolean hasTransformationMapProvenance();
  /**
   * <code>.olcut.RootProvenanceProto transformationMapProvenance = 4;</code>
   * @return The transformationMapProvenance.
   */
  com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProto getTransformationMapProvenance();
  /**
   * <code>.olcut.RootProvenanceProto transformationMapProvenance = 4;</code>
   */
  com.oracle.labs.mlrg.olcut.config.protobuf.protos.RootProvenanceProtoOrBuilder getTransformationMapProvenanceOrBuilder();
}
