// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tribuo-multilabel-core.proto

package org.tribuo.multilabel.protos;

public final class TribuoMultilabelCore {
  private TribuoMultilabelCore() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tribuo_multilabel_MultiLabelProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tribuo_multilabel_MultiLabelProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tribuo_multilabel_MutableMultiLabelInfoProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tribuo_multilabel_MutableMultiLabelInfoProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tribuo_multilabel_ImmutableMultiLabelInfoProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tribuo_multilabel_ImmutableMultiLabelInfoProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tribuo_multilabel_BinaryExampleProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tribuo_multilabel_BinaryExampleProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tribuo_multilabel_IndependentMultiLabelModelProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tribuo_multilabel_IndependentMultiLabelModelProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tribuo_multilabel_ClassifierChainModelProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tribuo_multilabel_ClassifierChainModelProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034tribuo-multilabel-core.proto\022\021tribuo.m" +
      "ultilabel\032\021tribuo-core.proto\"H\n\017MultiLab" +
      "elProto\022\r\n\005label\030\001 \003(\t\022\020\n\010lblScore\030\002 \003(\001" +
      "\022\024\n\014overallScore\030\003 \001(\001\"d\n\032MutableMultiLa" +
      "belInfoProto\022\r\n\005label\030\001 \003(\t\022\r\n\005count\030\002 \003" +
      "(\003\022\024\n\014unknownCount\030\003 \001(\005\022\022\n\ntotalCount\030\004" +
      " \001(\005\"r\n\034ImmutableMultiLabelInfoProto\022\r\n\005" +
      "label\030\001 \003(\t\022\r\n\005count\030\002 \003(\003\022\n\n\002id\030\003 \003(\005\022\024" +
      "\n\014unknownCount\030\004 \001(\005\022\022\n\ntotalCount\030\005 \001(\005" +
      "\"\254\001\n\022BinaryExampleProto\0220\n\rinner_example" +
      "\030\001 \001(\0132\031.tribuo.core.ExampleProto\022\'\n\005lab" +
      "el\030\002 \001(\0132\030.tribuo.core.OutputProto\022\016\n\006we" +
      "ight\030\003 \001(\002\022\024\n\014feature_name\030\004 \003(\t\022\025\n\rfeat" +
      "ure_value\030\005 \003(\001\"\243\001\n\037IndependentMultiLabe" +
      "lModelProto\022-\n\010metadata\030\001 \001(\0132\033.tribuo.c" +
      "ore.ModelDataProto\022\'\n\006models\030\002 \003(\0132\027.tri" +
      "buo.core.ModelProto\022(\n\006labels\030\003 \003(\0132\030.tr" +
      "ibuo.core.OutputProto\"\242\001\n\031ClassifierChai" +
      "nModelProto\022-\n\010metadata\030\001 \001(\0132\033.tribuo.c" +
      "ore.ModelDataProto\022\'\n\006models\030\002 \003(\0132\027.tri" +
      "buo.core.ModelProto\022-\n\013label_order\030\003 \003(\013" +
      "2\030.tribuo.core.OutputProtoB \n\034org.tribuo" +
      ".multilabel.protosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.tribuo.protos.core.TribuoCore.getDescriptor(),
        });
    internal_static_tribuo_multilabel_MultiLabelProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tribuo_multilabel_MultiLabelProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tribuo_multilabel_MultiLabelProto_descriptor,
        new java.lang.String[] { "Label", "LblScore", "OverallScore", });
    internal_static_tribuo_multilabel_MutableMultiLabelInfoProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tribuo_multilabel_MutableMultiLabelInfoProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tribuo_multilabel_MutableMultiLabelInfoProto_descriptor,
        new java.lang.String[] { "Label", "Count", "UnknownCount", "TotalCount", });
    internal_static_tribuo_multilabel_ImmutableMultiLabelInfoProto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tribuo_multilabel_ImmutableMultiLabelInfoProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tribuo_multilabel_ImmutableMultiLabelInfoProto_descriptor,
        new java.lang.String[] { "Label", "Count", "Id", "UnknownCount", "TotalCount", });
    internal_static_tribuo_multilabel_BinaryExampleProto_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tribuo_multilabel_BinaryExampleProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tribuo_multilabel_BinaryExampleProto_descriptor,
        new java.lang.String[] { "InnerExample", "Label", "Weight", "FeatureName", "FeatureValue", });
    internal_static_tribuo_multilabel_IndependentMultiLabelModelProto_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_tribuo_multilabel_IndependentMultiLabelModelProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tribuo_multilabel_IndependentMultiLabelModelProto_descriptor,
        new java.lang.String[] { "Metadata", "Models", "Labels", });
    internal_static_tribuo_multilabel_ClassifierChainModelProto_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_tribuo_multilabel_ClassifierChainModelProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tribuo_multilabel_ClassifierChainModelProto_descriptor,
        new java.lang.String[] { "Metadata", "Models", "LabelOrder", });
    org.tribuo.protos.core.TribuoCore.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
