name: Macaron check-github-actions

on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
  push:
    branches:
      - main
      - master
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
  workflow_dispatch:
  schedule:
    - cron: "17 4 * * 1"

permissions:
  contents: read

jobs:
  macaron-check-github-actions:
    name: Macaron policy verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Run Macaron check-github-actions policy
        uses: oracle/macaron@b31acfe389133a5587d9639063ec70cb84e7bc47 # v0.23.0
        with:
          repo_path: https://github.com/${{ github.repository }}
          policy_file: check-github-actions
          policy_purl: pkg:github/${{ github.repository }}@${{ github.sha }}

