# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Tribuo CI (Ubuntu aarch64, Java SE 21, 25)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        # test against supported LTS versions and latest
        java: [ 21, 25 ]
    name: Ubuntu Java SE ${{ matrix.java }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Setup Oracle Java SE
        uses: oracle-actions/setup-java@fff43251af9936a0e6a4d5d0946e14f1680e9b6b # v1.5.0
        with:
          website: oracle.com
          release: ${{ matrix.java }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Parm
